app = "hidayaai-backend"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[build]
  builder = "paketobuildpacks/python"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443